"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class cam_message_t(object):
    __slots__ = ["timestamp", "robot_pos", "obs_1_pos", "obs_2_pos", "obs_3_pos"]

    __typenames__ = ["int64_t", "float", "float", "float", "float"]

    __dimensions__ = [None, [3], [3], [3], [3]]

    def __init__(self):
        self.timestamp = 0
        self.robot_pos = [ 0.0 for dim0 in range(3) ]
        self.obs_1_pos = [ 0.0 for dim0 in range(3) ]
        self.obs_2_pos = [ 0.0 for dim0 in range(3) ]
        self.obs_3_pos = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(cam_message_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>3f', *self.robot_pos[:3]))
        buf.write(struct.pack('>3f', *self.obs_1_pos[:3]))
        buf.write(struct.pack('>3f', *self.obs_2_pos[:3]))
        buf.write(struct.pack('>3f', *self.obs_3_pos[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cam_message_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cam_message_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = cam_message_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.robot_pos = struct.unpack('>3f', buf.read(12))
        self.obs_1_pos = struct.unpack('>3f', buf.read(12))
        self.obs_2_pos = struct.unpack('>3f', buf.read(12))
        self.obs_3_pos = struct.unpack('>3f', buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if cam_message_t in parents: return 0
        tmphash = (0xf0ff63936de09024) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if cam_message_t._packed_fingerprint is None:
            cam_message_t._packed_fingerprint = struct.pack(">Q", cam_message_t._get_hash_recursive([]))
        return cam_message_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", cam_message_t._get_packed_fingerprint())[0]

